### ISSUE TITLE
Convert the content of text boxes and checkboxes into JSON-LD

### ISSUE THREAD

**Issue by keesvanbochove** [tk26/web-playground#3]
Example:
`{ "@context" : "schema.org",
"@type" : "ScholarlyArticle",
"@id" : "https://openpid.org/SA3542",
"url" : "ipfs://bafy"
"cid" : "bafy..."

"creator": [
    {
      "@type": "Person", 
      "@id": "https://orcid.org/0000-0002-8589-0609"
    }
]

"creator": [
    {
      "@type": "Person", 
      "name": "Neal D. Goldstein",
     "affiliation": "University of Chicago"
    }
]`

**Comment by tk26** [comment]
done by @keesvanbochove
